// 브랜드 명세 항목. 원본은 설계 6.1(기본 10개)과 9.3(전 컴포넌트 분석으로 더한 항목)이다.
// 명세 페이지(Task 19)가 항목마다 설명·지금 값·입력창을 그리고, skill(Task 20)과 반영 검사(Task 14, 26)가 hook·브리지 변수를 읽는다.
// hook 이름은 SLDS 2 CSS나 기본 컴포넌트 CSS가 var()로 읽는 이름만 쓴다(tests/spec-items.test.ts가 확인)
// 브라우저(Storybook)에서도 import하므로 Node 모듈을 쓰지 않는다
import { BRIDGE_VARS as B } from "./bridge-vars.ts";

export type SpecItem = {
  id: string;
  group: "기본" | "색" | "모양" | "크기" | "글자" | "깊이" | "움직임" | "포커스" | "아이콘" | "표시만";
  label: string;
  description: string;
  examples: string[];
  hooks: string[];
  bridgeVars: string[];
  limits: string;
  input: "text" | "color" | "path" | "none";
  /** 브리지에 기대는 부분이 있어 native 전환 때 그 부분을 잃는다(설계 5.6). bridgeVars가 있으면 참이다 */
  nativeLoss: boolean;
};

const g = (name: string) => `--slds-g-${name}`;
const c = (name: string) => `--slds-g-color-${name}`;
const s = (name: string) => `--slds-s-${name}`;
const steps = (prefix: string, ns: (number | string)[]) => ns.map((n) => `${prefix}${n}`);

const MOTION_DURATIONS = [B["motion-duration-fast"], B["motion-duration-medium"], B["motion-duration-slow"]];

const items: Omit<SpecItem, "nativeLoss">[] = [
  // 설계 6.1
  {
    id: "brand-color",
    group: "기본",
    label: "브랜드 색",
    description: "버튼·링크에 쓰는 색. 포커스 링 색과 아바타 이니셜 배경도 이 색을 따른다",
    examples: ["신뢰감 있는 딥그린"],
    hooks: [],
    bridgeVars: [],
    limits: "org 테마(BrandingSet의 BRAND_COLOR)가 원본이다. Salesforce는 입력한 색 대신 버튼에 접근성 색(50단계), 링크에 40단계를 쓴다",
    input: "text",
  },
  {
    id: "logo",
    group: "기본",
    label: "로고",
    description: "org 상단 로고",
    examples: ["assets/logo.png"],
    hooks: [],
    bridgeVars: [],
    limits: "contentassets/<이름>Logo.asset으로 복사하고 BRAND_IMAGE는 /file-asset/<이름>Logo?v=1이다",
    input: "path",
  },
  {
    id: "radius",
    group: "기본",
    label: "모서리",
    description: "버튼, 입력창, 카드의 반경. 각진 / 기본 / 둥근 3단계",
    examples: ["각지게", "둥글게"],
    hooks: steps(g("radius-border-"), [1, 2, 3, 4, "pill"]),
    bridgeVars: [B["path-end-radius"]],
    limits: "Path 양 끝 반경은 hook이 없어 브리지로 바꾼다",
    input: "text",
  },
  {
    id: "density",
    group: "기본",
    label: "밀도",
    description: "버튼·입력·라벨 간격과 간격 단계(spacing-1~12) 배율. 기본 / 촘촘",
    examples: ["촘촘하게"],
    hooks: [
      ...steps(g("spacing-"), [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
      s("button-spacing-inline"),
      s("button-spacing-block"),
      s("input-spacing"),
      s("label-spacing-gap"),
    ],
    bridgeVars: [],
    limits: "",
    input: "text",
  },
  {
    id: "typography",
    group: "기본",
    label: "글자",
    description: "기본 크기(13px)와 크기 단계, 제목·라벨 굵기",
    examples: ["제목과 라벨을 굵게"],
    hooks: [
      ...steps(g("font-scale-"), ["neg-2", "neg-1", "base", 1, 2, 3, 4, 5, 6, 7]),
      s("container-heading-font-weight"),
      s("pageheader-title-font-weight"),
      s("label-font-weight"),
    ],
    bridgeVars: [B["choice-label-weight"]],
    limits: "라디오·체크박스 라벨 굵기는 hook이 없어 브리지로 바꾼다. 글꼴은 바꾸지 않는다",
    input: "text",
  },
  {
    id: "feedback",
    group: "기본",
    label: "피드백 색",
    description: "성공·경고·오류·정보의 글자색·배경색",
    examples: ["성공은 글자 #1B5E20, 배경 #E8F5E9"],
    // 설계 5.3 표. lib/rules.ts의 FEEDBACK_HOOKS와 같다(이 파일은 브라우저에서도 쓰여 rules.ts를 import하지 않는다)
    hooks: [
      c("success-1"),
      c("on-success-1"),
      c("success-container-1"),
      c("border-success-1"),
      c("success-container-2"),
      c("warning-1"),
      c("on-warning-1"),
      c("warning-container-1"),
      c("error-1"),
      c("on-error-1"),
      c("error-container-1"),
      c("border-error-1"),
      c("error-container-2"),
      c("border-error-2"),
      c("on-info-1"),
      c("info-container-1"),
    ],
    bridgeVars: [],
    limits: "글자색은 배경 위와 흰색 위에서 모두 4.5:1 이상이어야 한다. 테두리는 따로 정하지 않으면 글자색을 따른다(성공·오류)",
    input: "color",
  },
  {
    id: "component",
    group: "기본",
    label: "컴포넌트별 조정",
    description: "버튼, 입력창, 카드의 반경과 그림자. 모달 너비(원할 때만)",
    examples: ["카드만 그림자 없이"],
    hooks: [
      s("button-radius-border"),
      s("input-radius-border"),
      s("container-radius-border"),
      s("button-shadow"),
      s("input-shadow"),
      s("container-shadow"),
    ],
    bridgeVars: [B["modal-width-medium"], B["modal-width-large"]],
    limits: "카드 그림자(--slds-s-container-shadow)는 native lightning-card에 닿지 않는다. 모달 너비는 hook이 없어 브리지로 바꾼다",
    input: "text",
  },
  {
    id: "milvus-component",
    group: "기본",
    label: "밀버스 컴포넌트",
    description: "예: milvusButton 커스텀 모드",
    examples: ["milvusButton은 커스텀 모드로"],
    hooks: [],
    bridgeVars: [],
    limits: "모양만 바꾸려고 밀버스 컴포넌트를 새로 만들지 않는다(설계 5.1)",
    input: "text",
  },
  {
    id: "font",
    group: "기본",
    label: "글꼴",
    description: "시스템 글꼴 고정",
    examples: [],
    hooks: [],
    bridgeVars: [],
    limits: "글꼴은 바꾸지 않는다(설계 1장)",
    input: "none",
  },
  {
    id: "overall",
    group: "기본",
    label: "전체 스타일",
    description: "원하는 전체 느낌",
    examples: ["각지고 단단한 업무용 느낌, 촘촘하게"],
    hooks: [],
    bridgeVars: [],
    limits: "",
    input: "text",
  },

  // 설계 9.3 — 색
  {
    id: "surface",
    group: "색",
    label: "바탕·면 색",
    description: "페이지 바탕(surface-2가 앱 바탕)과 카드·컨테이너 면",
    examples: ["페이지 바탕을 따뜻한 연회색으로", "카드는 아이보리"],
    hooks: [
      ...steps(c("surface-"), [1, 2, 3]),
      ...steps(c("surface-container-"), [1, 2, 3]),
      ...steps(c("neutral-base-"), [100, 95, 90]),
    ],
    bridgeVars: [],
    limits: "neutral-base-100/-95/-90은 native용이다. neutral-base-100은 색 위의 흰 글자로도 쓰여 흰색에 가까운 범위에서만 바꾼다",
    input: "text",
  },
  {
    id: "text-color",
    group: "색",
    label: "글자색 단계",
    description: "제목·본문(on-surface-3), 입력값·라벨(on-surface-2), 보조·placeholder(on-surface-1)",
    examples: ["글자를 남색 말고 거의 검정으로"],
    hooks: steps(c("on-surface-"), [3, 2, 1]),
    bridgeVars: [],
    limits: "보조 아이콘 색이 on-surface-1을 같이 쓴다. 대비 4.5:1을 검사한다",
    input: "text",
  },
  {
    id: "border-color",
    group: "색",
    label: "테두리·구분선",
    description: "구분선·카드(border-1), 입력·버튼(border-2)",
    examples: ["구분선은 옅게, 입력창 테두리는 진하게"],
    hooks: [c("border-1"), c("border-2"), c("border-base-1"), c("border-base-4")],
    bridgeVars: [],
    limits: "border-base-1/-4는 native용이다. native 일부는 하드코딩이다",
    input: "text",
  },
  {
    id: "neutral-tone",
    group: "색",
    label: "회색 온도",
    description: "neutral-base 단계와 의미 hook을 skill이 한 색조로 계산한다",
    examples: ["회색을 전부 쿨그레이로"],
    // SLDS 2는 16단계를 정의하지만 15·45·55단계는 읽는 곳이 없어 뺀다
    hooks: steps(c("neutral-base-"), [0, 10, 20, 30, 40, 50, 60, 65, 70, 80, 90, 95, 100]),
    bridgeVars: [],
    limits: "",
    input: "text",
  },
  {
    id: "disabled",
    group: "색",
    label: "비활성 상태",
    description: "비활성 요소의 바탕·글자·테두리",
    examples: ["비활성 버튼은 더 흐리게"],
    hooks: [
      ...steps(c("disabled-container-"), [1, 2]),
      ...steps(c("on-disabled-"), [1, 2]),
      ...steps(c("border-disabled-"), [1, 2]),
      ...steps(c("disabled-"), [1, 2]),
    ],
    bridgeVars: [],
    limits: "",
    input: "text",
  },
  {
    id: "inverse",
    group: "색",
    label: "어두운 면",
    description: "툴팁 같은 어두운 면의 바탕·글자·테두리",
    examples: ["툴팁을 남색 말고 차콜로"],
    hooks: [
      ...steps(c("surface-inverse-"), [1, 2]),
      ...steps(c("surface-container-inverse-"), [1, 2]),
      ...steps(c("on-surface-inverse-"), [1, 2]),
      ...steps(c("border-inverse-"), [1, 2]),
    ],
    bridgeVars: [],
    limits: "native 툴팁은 고정이다",
    input: "text",
  },
  {
    id: "backdrop",
    group: "색",
    label: "모달 배경막",
    description: "지금(--slds-s-backdrop-color-background)과 native(--slds-g-color-neutral-10-opacity-50)에 같은 값을 넣는다",
    examples: ["모달 뒤 막을 더 연하게"],
    hooks: [s("backdrop-color-background"), c("neutral-10-opacity-50")],
    bridgeVars: [],
    limits: "",
    input: "text",
  },
  {
    id: "highlight",
    group: "색",
    label: "검색어 강조",
    description: "검색어를 칠하는 노란색",
    examples: ["형광 노랑 말고 연한 살구색"],
    hooks: [c("palette-yellow-90"), c("palette-yellow-80")],
    bridgeVars: [],
    limits: "native 일부는 고정이다",
    input: "text",
  },
  {
    id: "hover-selected",
    group: "색",
    label: "hover·선택 바탕",
    description: "목록·표·메뉴의 hover와 선택 바탕",
    examples: ["목록 hover를 회색으로"],
    hooks: [
      c("surface-container-2"),
      c("surface-container-3"),
      s("menu-item-color-background-active"),
      s("table-row-color-background-selected"),
      s("navigation-color-background-hover"),
      s("pill-color-background-hover"),
      s("button-color-background-hover"),
    ],
    bridgeVars: [],
    limits: "native에서는 2개만 닿는다",
    input: "text",
  },
  {
    id: "dark-mode",
    group: "색",
    label: "다크 모드",
    description: "모든 색을 light-dark(라이트, 다크)로 쓴다",
    examples: ["다크 모드는 기본값 그대로"],
    hooks: [],
    bridgeVars: [],
    limits: "",
    input: "text",
  },

  // 설계 9.3 — 모양
  {
    id: "border-width",
    group: "모양",
    label: "테두리 두께",
    description: "기본 테두리(sizing-border-1)와 강조선(sizing-border-2)",
    examples: ["전체 테두리를 2px로"],
    hooks: [g("sizing-border-1"), g("sizing-border-2"), s("button-sizing-border")],
    bridgeVars: [B["input-border-width"]],
    limits: "--slds-s-button-sizing-border는 native 버튼용이다. 입력창 두께는 hook이 없어 브리지로 바꾼다",
    input: "text",
  },
  {
    id: "avatar-icon-shape",
    group: "모양",
    label: "아바타·개체 아이콘 모양",
    description: "프로필 사진과 개체 아이콘 배경의 반경",
    examples: ["프로필 사진을 둥근 사각으로"],
    hooks: [s("avatar-radius-border"), s("icon-radius-border")],
    bridgeVars: [],
    limits: "",
    input: "text",
  },
  {
    id: "tab-header-shape",
    group: "모양",
    label: "탭·페이지 헤더 모양",
    description: "선택된 탭 표시선, 탭과 페이지 헤더의 반경·테두리",
    examples: ["선택된 탭 밑줄을 2px로"],
    hooks: [
      s("navigation-sizing-border-active"),
      s("navigation-sizing-border-hover"),
      s("navigation-radius-border"),
      s("pageheader-radius-border"),
      s("pageheader-sizing-border"),
    ],
    bridgeVars: [],
    limits: "native tabBar는 고정이다",
    input: "text",
  },

  // 설계 9.3 — 크기
  {
    id: "control-height",
    group: "크기",
    label: "컨트롤 높이",
    description: "버튼·입력창·선택·콤보박스의 높이",
    examples: ["버튼과 입력창을 40px로"],
    hooks: [s("button-spacing-block"), s("input-sizing-height")],
    bridgeVars: [B["control-height"]],
    limits: "입력·선택·콤보는 브리지로 바꾼다. --slds-s-input-sizing-height는 native용이다. 브리지 없이 버튼만 키우면 폼에서 높이가 어긋난다",
    input: "text",
  },
  {
    id: "tab-header-height",
    group: "크기",
    label: "탭·헤더 높이",
    description: "탭 바와 헤더의 높이",
    examples: ["탭 바를 낮게"],
    hooks: [s("navigation-sizing-height"), s("navigation-font-lineheight"), s("header-sizing-height")],
    bridgeVars: [],
    limits: "",
    input: "text",
  },
  {
    id: "icon-size",
    group: "크기",
    label: "아이콘 크기",
    description: "기본 아이콘 크기와 배경 여백, 버튼·입력창 안 아이콘 크기",
    examples: ["기본 아이콘을 36px로"],
    hooks: [s("icon-sizing"), s("icon-spacing")],
    bridgeVars: [B["control-icon-size"]],
    limits: "버튼·입력창 안 아이콘 크기는 hook이 없어 브리지로 바꾼다",
    input: "text",
  },

  // 설계 9.3 — 글자
  {
    id: "line-height",
    group: "글자",
    label: "줄 간격",
    description: "본문(line-height-base), 제목(-2), 한 줄 요소(-1)",
    examples: ["본문 줄 간격 1.6"],
    hooks: [g("font-line-height-base"), g("font-line-height-2"), g("font-line-height-1")],
    bridgeVars: [],
    limits: "컨트롤 안 줄 간격은 고정이다",
    input: "text",
  },
  {
    id: "letter-spacing",
    group: "글자",
    label: "자간",
    description: ":root의 letter-spacing과 브리지(button, input, select, textarea)",
    examples: ["한글 자간 -0.02em"],
    hooks: [],
    bridgeVars: [B["letter-spacing"]],
    limits: "",
    input: "text",
  },
  {
    id: "text-case",
    group: "글자",
    label: "대소문자",
    description: "영문 대문자 제목(.slds-text-title_caps 등)의 대소문자",
    examples: ["영문 소제목을 대문자로 쓰지 마"],
    hooks: [],
    bridgeVars: [B["caps-transform"]],
    limits: "",
    input: "text",
  },

  // 설계 9.3 — 깊이
  {
    id: "shadow",
    group: "깊이",
    label: "그림자 깊이",
    description: "그림자 단계(shadow-1~4)와 방향형 그림자, 팝오버 꼬리 그림자",
    examples: ["그림자 없이 평평하게"],
    hooks: [
      ...steps(g("shadow-"), [1, 2, 3, 4]),
      ...["block-start", "block-end", "inline-start", "inline-end"].flatMap((d) => steps(g(`shadow-${d}-`), [1, 2, 3, 4])),
    ],
    bridgeVars: [B["nubbin-shadow"]],
    limits: "shadow-5/-6은 포커스 표시에 쓰여 기본값을 유지한다. 팝오버 꼬리는 브리지로 바꾼다. native 드롭다운·팝오버·툴팁은 고정이다",
    input: "text",
  },
  {
    id: "hover-press",
    group: "깊이",
    label: "hover·눌림 효과",
    description: "버튼 떠오름과 hover·눌림 그림자, 체크된 표시의 그림자",
    examples: ["버튼이 떠오르지 않게"],
    hooks: [
      s("button-brand-transform-hover"),
      s("button-bordered-transform-hover"),
      s("button-brand-shadow-hover"),
      s("button-bordered-shadow-hover"),
      s("button-shadow-hover"),
      s("button-shadow-active"),
      s("mark-shadow-checked"),
    ],
    bridgeVars: [],
    limits: "native에는 떠오름이 없다",
    input: "text",
  },

  // 설계 9.3 — 움직임 (hook이 없어 브리지로만 된다)
  {
    id: "motion-speed",
    group: "움직임",
    label: "속도",
    description: "fast(원래 0.1s 이하인 규칙), medium(0.15~0.2s), slow(0.25~0.4s). 기본값은 규칙마다 원래 값이다",
    examples: ["빠르고 경쾌하게", "차분하게"],
    hooks: [],
    bridgeVars: MOTION_DURATIONS,
    limits: "지금 org에서만 된다. 모달·토스트는 최소 0.01ms, 스피너는 제외",
    input: "text",
  },
  {
    id: "motion-easing",
    group: "움직임",
    label: "곡선",
    description: "움직임의 가속·감속 곡선",
    examples: ["부드럽게 감속하며"],
    hooks: [],
    bridgeVars: [B["motion-easing"]],
    limits: "지금 org에서만 된다. 스피너는 제외",
    input: "text",
  },
  {
    id: "reduced-motion",
    group: "움직임",
    label: "줄인 움직임",
    description: "브리지의 prefers-reduced-motion 규칙은 항상 켜 있다. 선택하면 항상 최소화한다(시간 변수를 0.01ms로)",
    examples: ["동작 줄이기를 켠 사람에게는 애니메이션 없이"],
    hooks: [],
    bridgeVars: MOTION_DURATIONS,
    limits: "0이 아니라 0.01ms를 쓴다. 0이면 모달·토스트가 닫히지 않을 수 있다",
    input: "text",
  },

  // 설계 9.3 — 포커스
  {
    id: "focus-ring",
    group: "포커스",
    label: "포커스 링 모양",
    description: "포커스 그림자 4종과 native용 s *-shadow-focus",
    examples: ["포커스 링을 3px로 굵게"],
    hooks: [
      g("shadow-outline-focus-1"),
      g("shadow-outset-focus-1"),
      g("shadow-inset-focus-1"),
      g("shadow-inset-inverse-focus-1"),
      s("button-shadow-focus"),
      s("input-shadow-focus"),
      s("mark-shadow-focus"),
    ],
    bridgeVars: [],
    limits: "링 색은 브랜드 색을 따른다. 값 안의 색은 var(--slds-g-color-brand-base-15)와 var(--slds-g-color-neutral-base-100)만 쓴다",
    input: "text",
  },
  {
    id: "cursor-underline",
    group: "포커스",
    label: "커서·링크 밑줄",
    description: "비활성 요소의 커서와 링크 hover 밑줄",
    examples: ["링크에 밑줄 없이"],
    hooks: [],
    bridgeVars: [B["cursor-disabled"], B["link-decoration-hover"]],
    limits: "",
    input: "text",
  },

  // 설계 9.3 — 아이콘
  {
    id: "object-icon-color",
    group: "아이콘",
    label: "개체 아이콘 색",
    description: "브리지가 클래스마다 아이콘 배경 hook을 다시 정의한다(원래 색이 기본값)",
    examples: ["Account 아이콘을 브랜드 남색으로"],
    hooks: [],
    bridgeVars: [B["icon-color-all"]],
    limits: "개체를 색으로 구분하던 단서가 사라질 수 있다",
    input: "text",
  },

  // 설계 9.3 — 표시만
  {
    id: "fixed",
    group: "표시만",
    label: "Salesforce 고정",
    description: "바꿀 수 없는 항목이다. 설계 9.4 목록(FIXED_ITEMS)을 보여 준다",
    examples: ["토스트를 10초 동안"],
    hooks: [],
    bridgeVars: [],
    limits: "",
    input: "none",
  },
];

export const SPEC_ITEMS: SpecItem[] = items.map((i) => ({ ...i, nativeLoss: i.bridgeVars.length > 0 }));
